version: "3.3"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - phpfpm
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./logs/nginx:/var/log/nginx/

  phpfpm:
    image: php:fpm
    ports:
      - "9000:9000"
    volumes:
      - ./projects:/var/www/html/

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 8183:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
